/* poolpayminer: Riecoin dispatch, see Dispatch.h */
#include "riecoin/Dispatch.h"
#include "base/io/json/Json.h"
#include "3rdparty/rapidjson/document.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>

#ifdef _WIN32
#   include <windows.h>
#else
#   include <unistd.h>
#   include <sys/wait.h>
#endif


namespace xmrig {
namespace riecoin {


namespace {


bool isRiecoinAlgo(const std::string &algo)
{
    std::string a;
    a.reserve(algo.size());
    for (char c : algo) a.push_back(static_cast<char>(::tolower(static_cast<unsigned char>(c))));

    return a == "ric" || a == "riecoin" || a == "riecoin/ric";
}


// argv[i] == flag (e.g. "-a"): value is argv[i + 1]. argv[i] == "--long=value" or "--long": value follows the same way.
bool matchOpt(const char *arg, const char *shortFlag, const char *longFlag, const char *&inlineValue)
{
    inlineValue = nullptr;

    if (shortFlag && strcmp(arg, shortFlag) == 0) {
        return true;
    }

    if (longFlag) {
        const size_t len = strlen(longFlag);
        if (strncmp(arg, longFlag, len) == 0) {
            if (arg[len] == '\0') {
                return true;
            }

            if (arg[len] == '=') {
                inlineValue = arg + len + 1;
                return true;
            }
        }
    }

    return false;
}


// The exe's own directory, with a trailing separator, so rieMiner is found next to poolpayminer regardless of
// the working directory the user launched it from.
std::string exeDir()
{
    char path[4096] = {};

#   ifdef _WIN32
    const DWORD n = GetModuleFileNameA(nullptr, path, sizeof(path));
    if (n == 0 || n >= sizeof(path)) {
        return {};
    }
    const char sep = '\\';
#   else
    const ssize_t n = readlink("/proc/self/exe", path, sizeof(path) - 1);
    if (n <= 0) {
        return {};
    }
    path[n] = '\0';
    const char sep = '/';
#   endif

    std::string s(path);
    const size_t pos = s.find_last_of(sep);
    if (pos == std::string::npos) {
        return {};
    }

    return s.substr(0, pos + 1);
}


void splitHostPort(std::string url, std::string &host, std::string &port)
{
    // strip a scheme prefix if someone pasted a URL with one; poolpayminer's own -o never has one, but be forgiving
    const size_t scheme = url.find("://");
    if (scheme != std::string::npos) {
        url = url.substr(scheme + 3);
    }

    const size_t colon = url.find_last_of(':');
    if (colon == std::string::npos) {
        host = url;
        port.clear();
        return;
    }

    host = url.substr(0, colon);
    port = url.substr(colon + 1);
}


bool writeRieMinerConf(const std::string &path, const std::string &host, const std::string &port, const std::string &user, const std::string &pass)
{
    std::ofstream f(path, std::ios::out | std::ios::trunc);
    if (!f) {
        return false;
    }

    f << "# generated by poolpayminer, do not edit: it is overwritten on every start\n"
      << "Mode = Pool\n"
      << "Host = " << host << "\n"
      << "Port = " << (port.empty() ? "28338" : port) << "\n"
      << "Username = " << user << "\n"
      << "Password = " << (pass.empty() ? "x" : pass) << "\n";

    return f.good();
}


} // namespace


bool maybeDispatch(int argc, char **argv, int &exitCode)
{
    std::string algo, url, user, pass, configPath;
    bool haveAlgo = false;

    for (int i = 1; i < argc; ++i) {
        const char *arg = argv[i];
        const char *inlineValue = nullptr;

        if (matchOpt(arg, "-a", "--algo", inlineValue)) {
            haveAlgo = true;
            algo = inlineValue ? inlineValue : ((i + 1 < argc) ? argv[++i] : "");
        }
        else if (matchOpt(arg, "-o", "--url", inlineValue)) {
            url = inlineValue ? inlineValue : ((i + 1 < argc) ? argv[++i] : "");
        }
        else if (matchOpt(arg, "-u", "--user", inlineValue)) {
            user = inlineValue ? inlineValue : ((i + 1 < argc) ? argv[++i] : "");
        }
        else if (matchOpt(arg, "-p", "--pass", inlineValue)) {
            pass = inlineValue ? inlineValue : ((i + 1 < argc) ? argv[++i] : "");
        }
        else if (matchOpt(arg, "-c", "--config", inlineValue)) {
            configPath = inlineValue ? inlineValue : ((i + 1 < argc) ? argv[++i] : "");
        }
    }

    // config.json fallback: only consulted for fields the command line did not already set, same precedence
    // as poolpayminer's normal config (CLI overrides the file). Only pools[0] is looked at: this wrapper is for
    // the simple, single-pool case that "-a ric -o ... -u ... -p ..." itself covers.
    if (!configPath.empty() && (url.empty() || user.empty() || !haveAlgo)) {
        rapidjson::Document doc;
        if (Json::get(configPath.c_str(), doc) && doc.IsObject()) {
            const auto poolsIt = doc.FindMember("pools");
            if (poolsIt != doc.MemberEnd() && poolsIt->value.IsArray() && !poolsIt->value.Empty()) {
                const auto &pool = poolsIt->value[0];
                if (!haveAlgo) {
                    if (const char *a = Json::getString(pool, "algo")) { algo = a; haveAlgo = true; }
                }
                if (url.empty()) {
                    if (const char *u = Json::getString(pool, "url")) url = u;
                }
                if (user.empty()) {
                    if (const char *u = Json::getString(pool, "user")) user = u;
                }
                if (pass.empty()) {
                    if (const char *p = Json::getString(pool, "pass")) pass = p;
                }
            }
        }
    }

    if (!haveAlgo || !isRiecoinAlgo(algo)) {
        return false;
    }

    printf("poolpayminer: algorithm \"%s\" is Riecoin's prime constellation search, not RandomX: handing off to the bundled rieMiner.\n", algo.c_str());

    if (url.empty()) {
        fprintf(stderr, "poolpayminer: -o/--url (pool host:port) is required for Riecoin.\n");
        exitCode = 1;
        return true;
    }

    std::string host, port;
    splitHostPort(url, host, port);

    const std::string dir = exeDir();
#   ifdef _WIN32
    const std::string rieMinerPath = dir + "rieMiner.exe";
#   else
    const std::string rieMinerPath = dir + "rieMiner";
#   endif
    const std::string confPath = dir + "poolpayminer-ric.conf";

    std::ifstream check(rieMinerPath, std::ios::binary);
    if (!check.good()) {
        fprintf(stderr, "poolpayminer: rieMiner was not found next to this program (expected %s). Redownload the poolpayminer package: it ships rieMiner alongside it for Riecoin.\n", rieMinerPath.c_str());
        exitCode = 1;
        return true;
    }
    check.close();

    if (!writeRieMinerConf(confPath, host, port, user, pass)) {
        fprintf(stderr, "poolpayminer: could not write %s\n", confPath.c_str());
        exitCode = 1;
        return true;
    }

    std::string cmd = "\"" + rieMinerPath + "\" \"" + confPath + "\"";
#   ifdef _WIN32
    cmd = "\"" + cmd + "\""; // cmd.exe quirk: a quoted first token needs the whole command re-quoted once more
#   endif

    exitCode = std::system(cmd.c_str());
#   ifndef _WIN32
    if (exitCode != -1) {
        exitCode = WIFEXITED(exitCode) ? WEXITSTATUS(exitCode) : 1;
    }
#   endif

    return true;
}


} // namespace riecoin
} // namespace xmrig
