#!/usr/bin/env python3
# Turns a binary file into a small .cpp translation unit that embeds it as a byte array, so it links straight into
# poolpayminer instead of needing to be shipped as a second file next to it. Used at CMake configure time to embed
# rieMiner (see src/riecoin/Dispatch.cpp, which writes it back out to disk before running it): one downloaded file
# is enough for Riecoin now, instead of poolpayminer[.exe] and rieMiner[.exe] having to be kept together.
#
#   embed_binary.py <input-binary> <output.cpp> <symbol>
#
# Emits, in the xmrig::riecoin namespace:
#   extern const unsigned char <symbol>[];
#   extern const unsigned long <symbol>_len;
import sys


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: embed_binary.py <input-binary> <output.cpp> <symbol>", file=sys.stderr)
        return 1

    src_path, out_path, symbol = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src_path, "rb") as f:
        data = f.read()

    with open(out_path, "w", encoding="utf-8") as out:
        out.write("// generated by tools/embed_binary.py from %s -- do not edit\n" % src_path)
        out.write("namespace xmrig {\nnamespace riecoin {\n\n\n")
        out.write("extern const unsigned char %s[] = {\n" % symbol)

        line = []
        for i, byte in enumerate(data):
            line.append("%d," % byte)
            if len(line) == 20:
                out.write("".join(line) + "\n")
                line = []
        if line:
            out.write("".join(line) + "\n")

        out.write("};\n")
        out.write("extern const unsigned long %s_len = %dUL;\n\n\n" % (symbol, len(data)))
        out.write("} // namespace riecoin\n} // namespace xmrig\n")

    print("embedded %d bytes from %s into %s (symbol %s)" % (len(data), src_path, out_path, symbol))
    return 0


if __name__ == "__main__":
    sys.exit(main())
